import { Canvas, useFrame } from '@react-three/fiber'
import { Line, Sparkles } from '@react-three/drei'
import { useMemo, useRef, type CSSProperties } from 'react'
import { Color, Group, MathUtils, Vector3 } from 'three'
import type { DailyRecord, NutritionTarget } from '../../types'
import { getFoodDistribution, getMacroEnergyRatio, getMealDistribution, getMonthlyRecords, getWeeklyRecords } from '../../data/selectors'

const macroColors=['#e76f51','#7167d9','#ead06f']
const mealColors=['#c9a978','#e76f51','#7167d9','#87a7a0']
const clamp=(value:number,min=0,max=1)=>Math.max(min,Math.min(max,value))
const windowed=(progress:number,start:number,end:number)=>clamp((progress-start)/(end-start))

function GlassPlate({ratio,opacity=1}:{ratio:number;opacity?:number}){return <group rotation={[Math.PI/2,0,0]}><mesh><cylinderGeometry args={[2.05,2.05,.18,96]}/><meshPhysicalMaterial color="#dce7df" transparent opacity={.14*opacity} transmission={.88} roughness={.08} thickness={2.4} ior={1.35} clearcoat={1}/></mesh><mesh position={[0,.015,0]} scale={[1,Math.max(.02,clamp(ratio,0,1.15)),1]}><cylinderGeometry args={[1.72,1.72,.08,96]}/><meshPhysicalMaterial color={ratio>1?'#e8a36f':'#92b9a5'} transparent opacity={.38*opacity} transmission={.3} roughness={.28} emissive={ratio>1?'#7d3828':'#264d40'} emissiveIntensity={.16}/></mesh><mesh><torusGeometry args={[2.04,.045,12,96]}/><meshPhysicalMaterial color="#eeeade" transparent opacity={.72*opacity} transmission={.45} roughness={.12}/></mesh></group>}

function MealLayers({record,amount}:{record:DailyRecord;amount:number}){const data=getMealDistribution(record).filter(item=>item.calories>0);const total=Math.max(1,record.totalCalories);return <group>{data.map((item,index)=>{const share=item.calories/total;const z=(index-(data.length-1)/2)*(1.05*amount);return <mesh key={item.type} position={[0,0,z]} rotation={[Math.PI/2,0,index*.08]} scale={[.94,.94,1]}><cylinderGeometry args={[1.82,1.82,.08+share*.42,72]}/><meshPhysicalMaterial color={mealColors[index]} transparent opacity={.16+amount*.34} transmission={.55} roughness={.18} thickness={1}/></mesh>})}</group>}

function FoodFragments({record,amount}:{record:DailyRecord;amount:number}){const meal=[...record.meals].sort((a,b)=>b.totalCalories-a.totalCalories)[0];const foods=getFoodDistribution(meal?{...record,meals:[meal]}:record).slice(0,8);const total=Math.max(1,meal?.totalCalories??record.totalCalories);return <group rotation={[.18,-.2,0]}>{foods.map((food,index)=>{const angle=index/Math.max(1,foods.length)*Math.PI*2;const radius=.45+amount*(1.25+index%2*.35);const share=food.calories/total;return <mesh key={food.id} position={[Math.cos(angle)*radius,Math.sin(angle)*radius,(index%3-1)*.32*amount]} rotation={[angle*.3,angle,-angle*.2]} scale={[.45+share*1.7,.32+share*1.2,.12+share*.55]}><icosahedronGeometry args={[1,2]}/><meshPhysicalMaterial color={mealColors[index%mealColors.length]} transparent opacity={amount*.78} roughness={.38} transmission={.18}/></mesh>})}</group>}

function NutrientRibbons({record,amount}:{record:DailyRecord;amount:number}){const macro=getMacroEnergyRatio(record);const shares=[macro.proteinRatio,macro.carbsRatio,macro.fatRatio];return <group rotation={[amount*.35,0,0]}>{shares.map((share,index)=><mesh key={index} rotation={[[1.15,.1,.2],[.35,1,-.4],[-.45,.65,.8]][index] as [number,number,number]} scale={[1,1,1]}><torusGeometry args={[2.25+index*.22,.025+share*.16,10,110,Math.PI*(1.25+amount*.75)]}/><meshPhysicalMaterial color={macroColors[index]} transparent opacity={amount*(.38+share*.5)} transmission={.35} roughness={.28} side={2}/></mesh>)}</group>}

function WeeklyLandscape({records,target,amount}:{records:DailyRecord[];target:number;amount:number}){const week=getWeeklyRecords(records);return <group position={[0,-.4,-1.4]} rotation={[1.05,0,0]}>{week.map((record,index)=>{const ratio=record.totalCalories/target;return <mesh key={record.date} position={[(index-3)*.78,(ratio-.85)*1.4,(index-3)*-.32*amount]} scale={[.62,.62,.45+Math.abs(ratio-1)*1.5]}><cylinderGeometry args={[.46,.46,.12,32]}/><meshPhysicalMaterial color={ratio>1?'#d9795d':'#7770c8'} transparent opacity={amount*(.14+record.consistencyScore!*.005)} transmission={.5} roughness={.26}/></mesh>})}</group>}

function MonthlyRing({records,target,amount}:{records:DailyRecord[];target:number;amount:number}){const month=getMonthlyRecords(records);return <group rotation={[.9,0,0]}>{month.map((record,index)=>{const angle=index/month.length*Math.PI*2;const radius=3.15;const ratio=record.totalCalories/target;const consistency=(record.consistencyScore??0)/100;return <mesh key={record.date} position={[Math.cos(angle)*radius*amount,Math.sin(angle)*radius*amount,(1-amount)*-7]} rotation={[Math.PI/2,0,angle]} scale={[.34,.34,.2+Math.abs(ratio-1)*.9]}><cylinderGeometry args={[1,1,.25,32]}/><meshPhysicalMaterial color={ratio>1?'#d9795d':'#889d91'} transparent opacity={amount*(.12+consistency*.42)} transmission={.65} roughness={.18}/></mesh>})}</group>}

function Scene({progress,record,records,target,reduced}:{progress:number;record:DailyRecord;records:DailyRecord[];target:NutritionTarget;reduced:boolean}){const root=useRef<Group>(null);const lens=useRef<Group>(null);const pointer=useRef({x:0,y:0});const ratio=target.targetCalories?record.totalCalories/target.targetCalories:0;const explode=windowed(progress,.19,.32)*(1-windowed(progress,.37,.48));const fragments=windowed(progress,.34,.47)*(1-windowed(progress,.54,.64));const ribbons=windowed(progress,.48,.61)*(1-windowed(progress,.68,.78));const weekly=windowed(progress,.66,.77)*(1-windowed(progress,.82,.91));const monthly=windowed(progress,.82,.96);const plateFade=1-windowed(progress,.68,.85);const points=useMemo(()=>Array.from({length:65},(_,i)=>new Vector3(Math.cos(i/64*Math.PI*2)*2.62,Math.sin(i/64*Math.PI*2)*2.62,0)),[]);useFrame((state,delta)=>{if(document.hidden||!root.current||!lens.current)return;pointer.current.x=MathUtils.lerp(pointer.current.x,state.pointer.x,.035);pointer.current.y=MathUtils.lerp(pointer.current.y,state.pointer.y,.035);const p=reduced?0:progress;root.current.rotation.y=MathUtils.lerp(root.current.rotation.y,pointer.current.x*.09+p*.5,.045);root.current.rotation.x=MathUtils.lerp(root.current.rotation.x,-pointer.current.y*.055,.045);lens.current.rotation.x=MathUtils.lerp(lens.current.rotation.x,p<.18?0:.28+p*.65,.04);lens.current.position.z=MathUtils.lerp(lens.current.position.z,p<.2?0:-.5,.04);root.current.rotation.z+=reduced?0:delta*.006});return <group ref={root}><ambientLight intensity={1.25}/><directionalLight position={[4,5,6]} intensity={4.5} color="#fff2d8"/><pointLight position={[-4,-2,4]} intensity={8} color="#7770c8"/><group ref={lens}><GlassPlate ratio={ratio} opacity={plateFade}/><MealLayers record={record} amount={explode}/><FoodFragments record={record} amount={fragments}/><NutrientRibbons record={record} amount={ribbons}/></group><WeeklyLandscape records={records} target={target.targetCalories} amount={weekly}/><MonthlyRing records={records} target={target.targetCalories} amount={monthly}/><Line points={points} color="#f2eee2" transparent opacity={.15*(1-monthly)} lineWidth={1}/><Sparkles count={reduced?0:innerWidth<700?260:900} scale={8} size={.8} speed={.08} color={new Color('#d8d4c8')} opacity={.2} noise={1.4}/></group>}

function StaticLens({ratio}:{ratio:number}){return <div className="static-lens" style={{'--fill':`${Math.min(100,ratio*100)}%`} as CSSProperties}><i/><span/></div>}
export function ImmersiveScene({progress,record,records,target,reduced=false}:{progress:number;record:DailyRecord;records:DailyRecord[];target:NutritionTarget;reduced?:boolean}){const ratio=target.targetCalories?record.totalCalories/target.targetCalories:0;const mobile=typeof window!=='undefined'&&window.innerWidth<700;if(mobile)return <div className="immersive-canvas mobile-static" aria-hidden="true"><StaticLens ratio={ratio}/></div>;return <div className="immersive-canvas" aria-hidden="true"><Canvas fallback={<StaticLens ratio={ratio}/>} dpr={[1,Math.min(1.75,window.devicePixelRatio)]} camera={{position:[0,0,7.4],fov:42}} gl={{alpha:true,antialias:true,powerPreference:'high-performance'}}><Scene progress={progress} record={record} records={records} target={target} reduced={reduced}/></Canvas></div>}
