import { useMemo, useState } from 'react'
import { scaleLinear, scaleSqrt } from 'd3'
import { motion } from 'motion/react'
import type { DailyRecord, NutritionTarget } from '../../types'
import { getCalorieDeviation, getDeviationSummary, getFoodScatterData, getMealRhythm, getMonthlyRecords, getTargetTernaryPoint, getTernaryPoint, getWeeklyRecords } from '../../data/selectors'

const mealNames={breakfast:'早餐',lunch:'午餐',dinner:'晚餐',snack:'加餐'}
const mealColors={breakfast:'#c9a978',lunch:'#e76f51',dinner:'#7167d9',snack:'#87a7a0'}
const point=(value:{x:number;y:number})=>({x:60+value.x*480,y:50+value.y*380})

export function NutritionTernary({record,records,target,onSelect}:{record:DailyRecord;records:DailyRecord[];target:NutritionTarget;onSelect?:(date:string)=>void}){const [hover,setHover]=useState('');const current=getTernaryPoint(record);const currentPoint=point(current);const ideal=point(getTargetTernaryPoint(target));const history=getWeeklyRecords(records).map(item=>({record:item,p:point(getTernaryPoint(item))}));return <div className="ternary-viz"><svg viewBox="0 0 600 500" role="img" aria-label="营养三角，展示三大营养素供能比例"><defs><linearGradient id="tri-fill" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#e76f51" stopOpacity=".16"/><stop offset=".5" stopColor="#7167d9" stopOpacity=".12"/><stop offset="1" stopColor="#ead06f" stopOpacity=".18"/></linearGradient></defs><path d="M300 50 L60 430 L540 430 Z" fill="url(#tri-fill)" stroke="currentColor" opacity=".72"/><path d="M300 145 L122 425 L478 425 Z" fill="none" stroke="currentColor" strokeDasharray="4 10" opacity=".16"/><text x="300" y="28" textAnchor="middle">蛋白质</text><text x="24" y="462">碳水</text><text x="576" y="462" textAnchor="end">脂肪</text><circle cx={ideal.x} cy={ideal.y} r="30" fill="none" stroke="#b9f23d" strokeDasharray="4 6" opacity=".75"/><text x={ideal.x} y={ideal.y+4} textAnchor="middle" className="target-label">目标区</text>{history.map(({record:item,p})=><circle key={item.date} cx={p.x} cy={p.y} r={item.date===record.date?0:6} fill="#c7c3b8" opacity=".32" onClick={()=>onSelect?.(item.date)}><title>{item.date} · {Math.round(item.totalCalories)} 千卡</title></circle>)}<motion.circle animate={{cx:currentPoint.x,cy:currentPoint.y}} transition={{duration:.55}} r="12" fill="#b9f23d" stroke="#11110f" strokeWidth="5" onMouseEnter={()=>setHover('today')} onMouseLeave={()=>setHover('')}/></svg><div className={`ternary-readout ${hover?'active':''}`}><b>{record.date.slice(5).replace('-','月')}日</b><span>蛋白质 {Math.round(current.proteinRatio*100)}%</span><span>碳水 {Math.round(current.carbsRatio*100)}%</span><span>脂肪 {Math.round(current.fatRatio*100)}%</span></div><p>越靠近某个顶点，说明该营养素提供的能量占比越高。虚线圆为个人目标结构。</p></div>}

export function FoodGalaxy({records}:{records:DailyRecord[]}){const [active,setActive]=useState('');const data=getFoodScatterData(records);const x=useMemo(()=>scaleLinear().domain([0,Math.max(250,...data.map(d=>d.kcalDensity))]).range([76,930]),[data]);const y=useMemo(()=>scaleLinear().domain([0,Math.max(35,...data.map(d=>d.proteinDensity))]).range([440,45]),[data]);const size=useMemo(()=>scaleSqrt().domain([0,Math.max(1,...data.map(d=>d.grams))]).range([5,28]),[data]);const selected=data.find(d=>d.id===active);return <div className="galaxy-viz"><svg viewBox="0 0 1000 520" role="img" aria-label="食物星图，横轴为热量密度，纵轴为蛋白质密度"><rect x="76" y="45" width="427" height="395" fill="#7167d9" opacity=".035"/><rect x="503" y="45" width="427" height="395" fill="#e76f51" opacity=".035"/><text x="95" y="72" className="zone">高蛋白 · 轻量区</text><text x="735" y="72" className="zone">高蛋白 · 能量密集区</text><text x="735" y="420" className="zone">高热量密度区</text>{[0,100,200,300,400,500,600].map(tick=><g key={tick}><line x1={x(tick)} x2={x(tick)} y1="45" y2="440" stroke="currentColor" opacity=".08"/><text x={x(tick)} y="475" textAnchor="middle">{tick}</text></g>)}{[0,10,20,30,40].map(tick=><g key={tick}><line x1="76" x2="930" y1={y(tick)} y2={y(tick)} stroke="currentColor" opacity=".08"/><text x="54" y={y(tick)+4} textAnchor="end">{tick}</text></g>)}<text x="500" y="510" textAnchor="middle" className="axis-title">单位重量热量 · 千卡 / 100克</text><text transform="translate(18 260) rotate(-90)" textAnchor="middle" className="axis-title">蛋白质密度 · 克 / 100克</text>{data.map((food,index)=><circle key={food.id} cx={x(food.kcalDensity)} cy={y(food.proteinDensity)} r={size(food.grams)} fill={['#e76f51','#7167d9','#ead06f','#87a7a0'][index%4]} opacity={active&&active!==food.id?.35:.72} onMouseEnter={()=>setActive(food.id)} onMouseLeave={()=>setActive('')}><title>{food.name} · {food.kcalDensity} 千卡/100克 · 蛋白质 {food.proteinDensity}克/100克 · 累计 {Math.round(food.grams)}克</title></circle>)}</svg>{selected&&<div className="galaxy-tooltip"><b>{selected.name}</b><span>{selected.kcalDensity} 千卡 / 100克</span><span>蛋白质 {selected.proteinDensity} 克 / 100克</span><em>累计摄入 {Math.round(selected.grams)} 克</em></div>}<p>横轴是单位重量热量，纵轴是单位重量蛋白质；圆点越大，过去 30 天实际摄入重量越多。</p></div>}

export function CircularMealRhythm({record,records}:{record:DailyRecord;records:DailyRecord[]}){const [mode,setMode]=useState<'today'|'week'>('today');const source=mode==='today'?[record]:getWeeklyRecords(records);const rhythm=getMealRhythm(source);const radial=(minutes:number,radius=174)=>{const a=minutes/1440*Math.PI*2-Math.PI/2;return{x:250+Math.cos(a)*radius,y:250+Math.sin(a)*radius}};return <div className="clock-viz"><div className="viz-toggle"><button className={mode==='today'?'active':''} onClick={()=>setMode('today')}>今日</button><button className={mode==='week'?'active':''} onClick={()=>setMode('week')}>七日</button></div><svg viewBox="0 0 500 500" role="img" aria-label="二十四小时圆形饮食节律"><circle cx="250" cy="250" r="174" fill="none" stroke="currentColor" opacity=".18"/><circle cx="250" cy="250" r="122" fill="none" stroke="currentColor" strokeDasharray="2 12" opacity=".12"/>{[['00:00',250,52],['06:00',448,255],['12:00',250,474],['18:00',52,255]].map(([label,x,y])=><text key={label} x={x} y={y} textAnchor="middle">{label}</text>)}{rhythm.map(item=>{const radius=mode==='today'?174:104+item.dayIndex*11;const p=radial(item.minutes,radius);const r=Math.max(5,Math.min(24,Math.sqrt(item.calories)*.72));return <circle key={`${item.date}-${item.id}`} cx={p.x} cy={p.y} r={r} fill={mealColors[item.type]} opacity={mode==='today'?.86:.18+item.dayIndex*.07}><title>{mealNames[item.type]} · {String(Math.floor(item.minutes/60)).padStart(2,'0')}:{String(item.minutes%60).padStart(2,'0')} · {Math.round(item.calories)} 千卡 · 占全天 {Math.round(item.share*100)}%</title></circle>})}<circle cx="250" cy="250" r="4" fill="#b9f23d"/></svg><p>Orb 角度表示进食时间，大小表示餐次热量。七日模式用同心轨迹呈现作息变化。</p></div>}

export function CalorieDeviationRibbon({records,target}:{records:DailyRecord[];target:number}){const data=getMonthlyRecords(records);const summary=getDeviationSummary(records,target);const x=scaleLinear().domain([0,Math.max(1,data.length-1)]).range([34,966]);const scale=Math.max(300,...data.map(record=>Math.abs(getCalorieDeviation(record,target))));const y=scaleLinear().domain([-scale,scale]).range([250,50]);const area=`M ${data.map((record,index)=>`${x(index)} ${y(getCalorieDeviation(record,target))}`).join(' L ')} L ${x(data.length-1)} ${y(0)} L ${x(0)} ${y(0)} Z`;return <div className="deviation-viz"><div className="deviation-stats"><div><b>{summary.within}</b><span>天在目标 ±10%</span></div><div><b>{summary.average>=0?'+':''}{summary.average}</b><span>平均偏差 · 千卡</span></div><div><b>+{summary.maximum}</b><span>最大超出</span></div><div><b>{summary.minimum}</b><span>最大低于</span></div></div><svg viewBox="0 0 1000 300" preserveAspectRatio="none" role="img" aria-label="三十日目标偏差带"><defs><linearGradient id="deviation-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#e76f51" stopOpacity=".5"/><stop offset=".5" stopColor="#c7c3b8" stopOpacity=".06"/><stop offset="1" stopColor="#7167d9" stopOpacity=".5"/></linearGradient></defs><path d={area} fill="url(#deviation-fill)"/><line x1="24" x2="976" y1={y(0)} y2={y(0)} stroke="#b9f23d" strokeDasharray="4 8"/><line x1="24" x2="976" y1={y(target*.1)} y2={y(target*.1)} stroke="currentColor" opacity=".1"/><line x1="24" x2="976" y1={y(-target*.1)} y2={y(-target*.1)} stroke="currentColor" opacity=".1"/>{data.map((record,index)=><circle key={record.date} cx={x(index)} cy={y(getCalorieDeviation(record,target))} r="3" fill={getCalorieDeviation(record,target)>0?'#e76f51':'#7167d9'}><title>{record.date} · {getCalorieDeviation(record,target)>0?'+':''}{Math.round(getCalorieDeviation(record,target))} 千卡</title></circle>)}</svg><p>中心线代表每日目标；上方为高于目标，下方为低于目标，浅线之间是 ±10% 范围。</p></div>}
