import { useEffect, useState } from 'react'
import { ArrowDown, ArrowUpRight, Edit3, Plus, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { motion, useReducedMotion, useScroll, useTransform } from 'motion/react'
import { CountUp } from '../components/CountUp'
import { EnergyCore } from '../components/EnergyCore'
import { EnergyRibbon, MealRhythmLine, NutritionBody } from '../components/TodayVisuals'
import { consumeEnergyInjection } from '../data/store'
import { useAppData } from '../hooks/useAppData'
import type { DailyRecord } from '../types'
import { todayKey } from '../utils'

const mealNames={breakfast:'早餐',lunch:'午餐',dinner:'晚餐',snack:'加餐'}
export function Dashboard(){const {target,records}=useAppData();const empty:DailyRecord={date:todayKey(),meals:[],totalCalories:0,protein:0,carbs:0,fat:0};const today=records.find(r=>r.date===todayKey())??empty;const remaining=target.targetCalories-today.totalCalories;const [injection,setInjection]=useState(false);const reduced=useReducedMotion();const {scrollYProgress}=useScroll();const lensScale=useTransform(scrollYProgress,[0,.18],[1,1.42]);const titleY=useTransform(scrollYProgress,[0,.16],[0,-80]);useEffect(()=>{if(consumeEnergyInjection()&&!reduced){setInjection(true);const id=setTimeout(()=>setInjection(false),1000);return()=>clearTimeout(id)}},[reduced]);const macros=[{label:'蛋白质',value:today.protein,target:target.proteinTarget,color:'#e76f51'},{label:'碳水',value:today.carbs,target:target.carbTarget,color:'#7167d9'},{label:'脂肪',value:today.fat,target:target.fatTarget,color:'#ead06f'}];return <motion.div className="today-page" initial={{opacity:0}} animate={{opacity:1}} transition={{duration:.7}}>
  <section className="lens-hero"><div className="depth-grid"/><motion.div className="hero-manifesto" style={{y:reduced?0:titleY}}>看见，<br/>你吃下的<br/><em>能量。</em></motion.div><div className="hero-meta"><span>CalorieLens 3.0</span><p>个人饮食能量可视化系统</p></div><motion.div className="hero-lens" style={{scale:reduced?1:lensScale}}><div className="lens-halo"/><EnergyCore calories={today.totalCalories} target={target.targetCalories} macros={macros} injection={injection}/></motion.div><div className="hero-live"><span>今日 · {new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric'})}</span><strong><CountUp value={today.totalCalories}/><small> 千卡</small></strong><p>能量正在成为可以看见的数据。</p><Link to="/record"><Plus/>记录这一餐</Link></div><a href="#energy-story" className="scroll-cue"><ArrowDown/>向下观察</a>{injection&&<div className="lens-injection"><Sparkles/>一餐数据正在进入今日</div>}</section>
  <section id="energy-story" className="energy-story"><header><span>01 / 今日能量</span><h2>数字之间，<br/>是你今天的余量。</h2></header><div className="giant-energy"><article><span>今日已摄入</span><strong><CountUp value={today.totalCalories}/></strong><small>千卡</small></article><div className="relation-line"><i style={{width:`${Math.min(100,today.totalCalories/target.targetCalories*100)}%`}}/></div><article><span>今日目标</span><strong><CountUp value={target.targetCalories}/></strong><small>千卡</small></article></div><div className="remaining-statement">今天，你还有 <strong><CountUp value={Math.abs(remaining)}/></strong> 千卡{remaining>=0?'的余量':'已超出目标'}。</div></section>
  <section className="editorial-section nutrition-section"><header><span>02 / 营养结构</span><h2>三种营养，<br/>共同塑造一个形态。</h2><p>外层虚线是目标，内部实体是今日。蛋白质影响纵向，碳水影响宽度，脂肪影响圆润程度。</p></header><NutritionBody record={today} target={target}/></section>
  <section className="editorial-section rhythm-section"><header><span>03 / 今日饮食节律</span><h2>一天的能量，<br/>在时间里留下节点。</h2></header><MealRhythmLine record={today}/></section>
  <section className="editorial-section meals-section"><header><span>04 / 今日餐食</span><h2>每一餐，都是<br/>能量轨迹的一部分。</h2></header><div className="meal-timeline">{[...today.meals].sort((a,b)=>a.timestamp.localeCompare(b.timestamp)).map((meal,index)=><article key={meal.id}><div className="meal-time">{new Date(meal.timestamp).toTimeString().slice(0,5)}<i/></div><div><span>{mealNames[meal.type]} · 0{index+1}</span><h3>{meal.foods.map(f=>f.name).join('、')}</h3><p>{meal.foods.map(f=>`${f.name} ${Math.round(f.grams)}克`).join('　')}</p></div><strong>{Math.round(meal.totalCalories)}<small> 千卡</small></strong><Link to={`/record?meal=${meal.id}`} aria-label="编辑这餐"><Edit3/></Link></article>)}{!today.meals.length&&<div className="no-meals"><p>今天还没有餐食记录。</p><Link to="/record">记录第一餐 <ArrowUpRight/></Link></div>}</div></section>
  <section className="editorial-section ribbon-section"><header><span>05 / 能量流向</span><h2>食物如何汇入今日，<br/>又如何接近目标。</h2></header><EnergyRibbon record={today} target={target.targetCalories}/></section>
  <footer className="today-footer"><span>CalorieLens</span><p>数据用于课程展示，不构成专业营养建议。</p><Link to="/trends">让时间显现规律 <ArrowUpRight/></Link></footer>
  </motion.div>}
