import { useRef, useState, type ChangeEvent, type DragEvent } from 'react'
import { AlertCircle, Check, ImagePlus, Plus, ScanLine, Sparkles, Trash2, Upload } from 'lucide-react'
import { AnimatePresence, motion } from 'motion/react'
import { useNavigate } from 'react-router-dom'
import type { EChartsOption } from 'echarts'
import { Card, PageHeader } from '../components/UI'
import { EChart } from '../components/EChart'
import { addMeal } from '../data/store'
import { FoodRecognitionService } from '../services/FoodRecognitionService'
import type { FoodItem, MealType, RecognitionResult } from '../types'
import { clampNumber, COLORS, recalculateFood, uid } from '../utils'
import { useAppUI } from '../context/AppUIContext'

const mealOptions:{value:MealType;label:string}[]=[{value:'breakfast',label:'早餐'},{value:'lunch',label:'午餐'},{value:'dinner',label:'晚餐'},{value:'snack',label:'零食'}]
export function Recognition(){
  const inputRef=useRef<HTMLInputElement>(null);const navigate=useNavigate();const {theme}=useAppUI();const [file,setFile]=useState<File>();const [preview,setPreview]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [progress,setProgress]=useState(0);const [result,setResult]=useState<RecognitionResult>();const [active,setActive]=useState('');const [showMeal,setShowMeal]=useState(false);const [added,setAdded]=useState(false)
  const accept=(chosen?:File)=>{setError('');setResult(undefined);setAdded(false);if(!chosen)return;if(!['image/jpeg','image/png','image/webp'].includes(chosen.type)){setError('仅支持 JPG、PNG 或 WEBP 图片。');return}if(chosen.size>10*1024*1024){setError('图片大小不能超过 10MB。');return}setFile(chosen);setPreview(URL.createObjectURL(chosen))}
  const analyze=async()=>{if(!file)return;setLoading(true);setProgress(4);setError('');const timer=setInterval(()=>setProgress(v=>Math.min(92,v+Math.max(2,Math.round((96-v)*.14)))),100);try{const next=await FoodRecognitionService.recognize(file);setProgress(100);setResult(next);setActive(next.items[0]?.id??'')}catch{setError('识别暂时不可用，请稍后重试。')}finally{clearInterval(timer);setTimeout(()=>setLoading(false),280)}}
  const update=(id:string,key:keyof FoodItem,value:string)=>setResult(r=>!r?r:{...r,items:r.items.map(item=>{if(item.id!==id)return item;const numeric=clampNumber(value);const next={...item,[key]:key==='name'?value:numeric};if(key==='protein')next.proteinPer100g=item.grams?numeric*100/item.grams:0;if(key==='carbs')next.carbsPer100g=item.grams?numeric*100/item.grams:0;if(key==='fat')next.fatPer100g=item.grams?numeric*100/item.grams:0;return recalculateFood(next)})})
  const total=result?.items.reduce((a,f)=>({calories:a.calories+f.calories,protein:a.protein+f.protein,carbs:a.carbs+f.carbs,fat:a.fat+f.fat}),{calories:0,protein:0,carbs:0,fat:0})??{calories:0,protein:0,carbs:0,fat:0}
  const macroEnergy={protein:total.protein*4,carbs:total.carbs*4,fat:total.fat*9};const macroTotal=Math.max(1,macroEnergy.protein+macroEnergy.carbs+macroEnergy.fat)
  const radial:EChartsOption={tooltip:{trigger:'item',formatter:'{b}: {c} 千卡 ({d}%)'},series:[{type:'pie',radius:['69%','84%'],center:['50%','50%'],startAngle:90,label:{show:false},data:[{name:'蛋白质',value:Math.round(macroEnergy.protein),itemStyle:{color:COLORS.green}},{name:'碳水',value:Math.round(macroEnergy.carbs),itemStyle:{color:COLORS.orange}},{name:'脂肪',value:Math.round(macroEnergy.fat),itemStyle:{color:COLORS.blue}}]}],graphic:[{type:'text',left:'center',top:'39%',style:{text:`${Math.round(total.calories)}`,fill:theme==='dark'?'#e9f0ec':COLORS.ink,font:'700 28px Inter'}},{type:'text',left:'center',top:'55%',style:{text:'总热量 / 千卡',fill:COLORS.muted,font:'10px Inter'}}]}
  const addFood=()=>setResult(r=>!r?r:{...r,items:[...r.items,{id:uid(),name:'新食物',grams:100,kcalPer100g:100,proteinPer100g:0,carbsPer100g:0,fatPer100g:0,calories:100,protein:0,carbs:0,fat:0,source:'manual'}]})
  const save=(type:MealType)=>{if(!result?.items.length)return;addMeal(type,result.items,preview);setShowMeal(false);setAdded(true);setTimeout(()=>navigate('/'),850)}
  const stage=progress<36?'分割食物区域':progress<70?'估算食物份量':'匹配营养数据'
  return <motion.div className="page vision-page" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{duration:.5}}><PageHeader eyebrow="智能图像识别" title="餐食视觉实验室" description="从图像像素到可编辑营养数据，再注入你的个人能量记录。"/>
    <div className="notice"><AlertCircle size={18}/><span>图片识别结果为估算值，你可以修改食物和份量以提高准确度。</span></div>
    <motion.div layout className={result?'lab-grid has-result':'lab-grid'}><motion.section layoutId="meal-image" className="lab-image card">
      {!preview?<div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={(e:DragEvent)=>{e.preventDefault();accept(e.dataTransfer.files[0])}} onClick={()=>inputRef.current?.click()}><div className="upload-icon"><ImagePlus size={29}/></div><h2>加载餐食图像</h2><p>拖拽图片到视觉分析区域</p><small>JPG / PNG / WEBP · MAX 10MB</small><button className="secondary-btn"><Upload size={17}/>选择图片</button></div>:<div className="vision-frame"><img src={preview} alt="餐食视觉识别画面"/>{loading&&<div className="scan-overlay"><div className="scan-grid"/><div className="scan-line"/><div className="scan-status"><ScanLine size={16}/><span>VISION ANALYSIS</span><b>{progress}%</b><i>{stage}</i></div></div>}{result&&result.items.map((item,index)=>{const box=result.boxes?.[item.name]??{x:8+(index%2)*46,y:10+Math.floor(index/2)*45,width:35,height:30};return <button key={item.id} onClick={()=>setActive(item.id)} className={`hotspot ${active===item.id?'active':''}`} style={{left:`${box.x}%`,top:`${box.y}%`,width:`${box.width}%`,height:`${box.height}%`}}><span>{item.name}<b>{item.grams}g · {Math.round((item.confidence??result.confidence)*100)}%</b></span></button>})}{result?.mode==='demo'&&<div className="demo-detection">DEMO VISUAL DETECTION</div>}</div>}
      <input ref={inputRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={(e:ChangeEvent<HTMLInputElement>)=>accept(e.target.files?.[0])}/>{error&&<p className="error-text">{error}</p>}{preview&&!result&&!loading&&<div className="lab-controls"><button className="secondary-btn" onClick={()=>inputRef.current?.click()}>更换图片</button><button className="primary-btn" onClick={analyze}><Sparkles size={17}/>启动 AI Scan</button></div>}
    </motion.section>
    <AnimatePresence>{result&&<motion.aside className="composition-panel card" initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} exit={{opacity:0}}><span className={`mode-badge ${result.mode}`}>{result.mode==='demo'?'Demo AI Result':'Real AI Result'}</span><h2>Meal Nutrition Composition</h2><p>{result.mealName} · {Math.round(result.confidence*100)}% confidence</p><EChart option={radial} height={220} ariaLabel="本餐营养能量来源环形图"/><div className="composition-legend"><span><i style={{background:COLORS.green}}/>Protein <b>{Math.round(macroEnergy.protein/macroTotal*100)}%</b></span><span><i style={{background:COLORS.orange}}/>Carbs <b>{Math.round(macroEnergy.carbs/macroTotal*100)}%</b></span><span><i style={{background:COLORS.blue}}/>Fat <b>{Math.round(macroEnergy.fat/macroTotal*100)}%</b></span></div><small>按 Protein × 4、Carbs × 4、Fat × 9 kcal 计算</small></motion.aside>}</AnimatePresence></motion.div>
    {result&&<motion.div className="result-section" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}}><div className="result-heading"><div><p className="eyebrow">DETECTION RESULT</p><h2>可编辑识别结果</h2><p>图像检测框与数据项支持双向联动</p></div></div><div className="food-list">{result.items.map((item,index)=><motion.div layout key={item.id} className={`food-editor card ${active===item.id?'active':''}`} onClick={()=>setActive(item.id)}><div className="food-index">{String(index+1).padStart(2,'0')}</div><div className="field name-field"><label>食物名称</label><input value={item.name} onChange={e=>update(item.id,'name',e.target.value)}/></div>{([['grams','重量','g'],['kcalPer100g','热量密度','kcal/100g'],['protein','蛋白质','g'],['carbs','碳水','g'],['fat','脂肪','g']] as const).map(([key,label,unit])=><div className="field" key={key}><label>{label}</label><div className="input-unit"><input type="number" min="0" value={item[key]} onChange={e=>update(item.id,key,e.target.value)}/><span>{unit}</span></div></div>)}<div className="calculated"><span>预计热量</span><strong>{item.calories} kcal</strong></div><button className="icon-btn danger-btn" onClick={e=>{e.stopPropagation();setResult(r=>!r?r:{...r,items:r.items.filter(f=>f.id!==item.id)})}}><Trash2 size={18}/></button></motion.div>)}</div><button className="add-food" onClick={addFood}><Plus size={17}/>添加食物</button>
      <Card className="meal-total"><div><span>DATA PAYLOAD</span><strong>{Math.round(total.calories)} <small>kcal</small></strong></div><div className="total-macros"><span><i className="green-dot"/>蛋白质 <b>{Math.round(total.protein)}g</b></span><span><i className="orange-dot"/>碳水 <b>{Math.round(total.carbs)}g</b></span><span><i className="blue-dot"/>脂肪 <b>{Math.round(total.fat)}g</b></span></div><div className="save-wrap"><button className="primary-btn" disabled={!result.items.length} onClick={()=>setShowMeal(v=>!v)}>Add to Today</button>{showMeal&&<motion.div className="meal-picker" initial={{opacity:0,scale:.98}} animate={{opacity:1,scale:1}}><p>选择餐次</p>{mealOptions.map(m=><button key={m.value} onClick={()=>save(m.value)}>{m.label}</button>)}</motion.div>}</div></Card>{added&&<motion.div className="success-toast" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}><Check size={18}/>营养数据已注入，正在返回 Metabolic Core…</motion.div>}
    </motion.div>}
  </motion.div>
}
