import { Canvas, useFrame } from '@react-three/fiber'
import { Line, OrbitControls, Sparkles } from '@react-three/drei'
import { useRef, useState } from 'react'
import { AdditiveBlending, Color, Group, Mesh, Vector3 } from 'three'
import { useReducedMotion } from 'motion/react'

type Macro={label:string;value:number;target:number;color:string}
const ringPoints=(radius:number,start:number,end:number,z=0)=>Array.from({length:65},(_,i)=>{const a=start+(end-start)*i/64;return new Vector3(Math.cos(a)*radius,Math.sin(a)*radius,z)})
function MacroOrbit({macro,index,onSelect}:{macro:Macro;index:number;onSelect?:(name:string)=>void}){const [hovered,setHovered]=useState(false);const pct=Math.min(1,macro.target?macro.value/macro.target:0);const rotation:[number,number,number]=[[1.12,.1,.2],[.35,.95,-.4],[-.45,.65,.8]][index] as [number,number,number];const radius=1.62+index*.19;return <group rotation={rotation}><Line points={ringPoints(radius,0,Math.PI*2)} color="#476158" opacity={.22} transparent lineWidth={1}/><Line points={ringPoints(radius,-Math.PI/2,-Math.PI/2+Math.PI*2*pct)} color={macro.color} lineWidth={hovered?3.2:2} onPointerOver={e=>{e.stopPropagation();setHovered(true)}} onPointerOut={()=>setHovered(false)} onClick={e=>{e.stopPropagation();onSelect?.(macro.label)}}/>{hovered&&<mesh position={[0,radius+.18,0]}><sphereGeometry args={[.055,12,12]}/><meshBasicMaterial color={macro.color}/></mesh>}</group>}
function Scene({ratio,macros,injection,onSelect}:{ratio:number;macros:Macro[];injection:boolean;onSelect?:(name:string)=>void}){const group=useRef<Group>(null);const core=useRef<Mesh>(null);const reduced=useReducedMotion();const quality=typeof navigator!=='undefined'&&navigator.hardwareConcurrency<=4?'low':'high';useFrame((state,delta)=>{if(!group.current||!core.current)return;if(!reduced)group.current.rotation.y+=delta*.045;const base=.83+Math.min(1.18,ratio)*.28;const pulse=ratio>1&&!reduced?Math.sin(state.clock.elapsedTime*(ratio>1.1?1.2:.7))*.025:0;core.current.scale.lerp(new Vector3(base+pulse,base+pulse,base+pulse),.035)});const coreColor=ratio>1.1?'#f1a65b':ratio>.7?'#45c983':'#61bfa0';return <group ref={group}><ambientLight intensity={1.1}/><pointLight position={[3,3,4]} intensity={18} color="#6ce0a2"/><mesh ref={core}><icosahedronGeometry args={[1,quality==='low'?3:5]}/><meshPhysicalMaterial color={new Color(coreColor)} transparent opacity={.5} roughness={.18} metalness={.06} transmission={.38} thickness={1.5} emissive={new Color(coreColor)} emissiveIntensity={.28+ratio*.22}/></mesh><mesh scale={.72}><sphereGeometry args={[1,32,32]}/><meshBasicMaterial color="#baf6d3" transparent opacity={.13} blending={AdditiveBlending}/></mesh><Sparkles count={quality==='low'?30:58} scale={1.65} size={1.5} speed={reduced?0:.12+ratio*.08} color="#d9ffea" opacity={.65}/>{injection&&!reduced&&<Sparkles count={28} scale={2.8} size={2.2} speed={1.1} color="#f7c880" opacity={.8}/>}<Line points={ringPoints(2.18,0,Math.PI*2)} color="#7d9b8e" opacity={.3} transparent lineWidth={1}/><Line points={ringPoints(2.18,-Math.PI/2,-Math.PI/2+Math.PI*2*Math.min(1,ratio))} color="#b7ead0" lineWidth={2}/>{macros.map((m,i)=><MacroOrbit key={m.label} macro={m} index={i} onSelect={onSelect}/>)}</group>}
export function EnergyCore({calories,target,macros,injection=false,onMacroSelect}:{calories:number;target:number;macros:Macro[];injection?:boolean;onMacroSelect?:(name:string)=>void}){const ratio=target?calories/target:0;return <div className="energy-core" aria-label={`热量透镜，今日摄入完成 ${Math.round(ratio*100)}%`}><Canvas dpr={[1,Math.min(1.7,window.devicePixelRatio)]} camera={{position:[0,0,6.2],fov:42}} gl={{alpha:true,antialias:true,powerPreference:'high-performance'}}><Scene ratio={ratio} macros={macros} injection={injection} onSelect={onMacroSelect}/><OrbitControls enablePan={false} enableZoom={false} minPolarAngle={Math.PI*.36} maxPolarAngle={Math.PI*.64} rotateSpeed={.22}/></Canvas><div className="core-readout"><span>今日能量密度</span><strong>{Math.round(ratio*100)}%</strong><small>摄入 / 目标</small></div></div>}
