import { Canvas, useFrame } from '@react-three/fiber'
import { Html, Line, OrbitControls } from '@react-three/drei'
import { useRef, useState } from 'react'
import type { DailyRecord } from '../types'
import { Color, Group, Mesh, Vector3 } from 'three'
import { useReducedMotion } from 'motion/react'

function Pillar({record,index,total,target,selected,onSelect}:{record:DailyRecord;index:number;total:number;target:number;selected:boolean;onSelect:(date:string)=>void}){const [hover,setHover]=useState(false);const mesh=useRef<Mesh>(null);const height=Math.max(.35,record.totalCalories/target*2.2);const x=(index-(total-1)/2)*.72;useFrame(()=>{if(mesh.current){const s=hover||selected?1.1:1;mesh.current.scale.x+=(s-mesh.current.scale.x)*.08;mesh.current.scale.z+=(s-mesh.current.scale.z)*.08}});return <group position={[x,height/2-1.15,0]}><mesh ref={mesh} onPointerOver={e=>{e.stopPropagation();setHover(true)}} onPointerOut={()=>setHover(false)} onClick={e=>{e.stopPropagation();onSelect(record.date)}}><cylinderGeometry args={[.2,.3,height,24]}/><meshStandardMaterial color={new Color(record.totalCalories>target?'#eba45f':'#42b77a')} roughness={.34} metalness={.08} transparent opacity={selected?1:.82}/></mesh>{(hover||selected)&&<Html center position={[0,height/2+.35,0]}><div className="landscape-tip"><b>{record.date.slice(5).replace('-','/')}</b><span>{record.totalCalories} kcal</span><em>{record.totalCalories-target>=0?'+':''}{record.totalCalories-target} kcal</em></div></Html>}</group>}
function LandscapeScene({data,target,selectedDate,onSelect}:{data:DailyRecord[];target:number;selectedDate:string;onSelect:(date:string)=>void}){const group=useRef<Group>(null);const reduced=useReducedMotion();useFrame(()=>{if(group.current&&!reduced)group.current.rotation.y=Math.sin(Date.now()/8000)*.025});const width=Math.max(3,(data.length-1)*.72);return <group ref={group}><ambientLight intensity={1.6}/><directionalLight position={[3,5,4]} intensity={2.1}/>{data.map((r,i)=><Pillar key={r.date} record={r} index={i} total={data.length} target={target} selected={r.date===selectedDate} onSelect={onSelect}/>)}<Line points={[new Vector3(-width/2,1.05,.02),new Vector3(width/2,1.05,.02)]} color="#f0b56f" lineWidth={2}/><mesh rotation={[-Math.PI/2,0,0]} position={[0,-1.15,0]}><planeGeometry args={[width+1,2.2]}/><meshStandardMaterial color="#23332c" transparent opacity={.08}/></mesh></group>}
export function NutritionLandscape({data,target,selectedDate,onSelect}:{data:DailyRecord[];target:number;selectedDate:string;onSelect:(date:string)=>void}){return <div className="landscape" aria-label="七日营养地形"><Canvas dpr={[1,1.5]} camera={{position:[0,2.8,7.2],fov:48}} gl={{alpha:true,antialias:true}}><LandscapeScene data={data} target={target} selectedDate={selectedDate} onSelect={onSelect}/><OrbitControls enablePan={false} enableZoom={false} minPolarAngle={.8} maxPolarAngle={1.35} rotateSpeed={.16}/></Canvas></div>}
