import { useState } from 'react'
import { motion } from 'motion/react'
import type { DailyRecord, NutritionTarget } from '../types'

export function NutritionBody({record,target}:{record:DailyRecord;target:NutritionTarget}){const [active,setActive]=useState('');const p=Math.min(1.25,target.proteinTarget?record.protein/target.proteinTarget:0);const c=Math.min(1.25,target.carbTarget?record.carbs/target.carbTarget:0);const f=Math.min(1.25,target.fatTarget?record.fat/target.fatTarget:0);const rx=112+c*58,ry=88+p*65,curve=32+f*45;const path=`M 250 ${200-ry} C ${250+rx} ${170-curve}, ${250+rx} ${230+curve}, 250 ${200+ry} C ${250-rx} ${230+curve}, ${250-rx} ${170-curve}, 250 ${200-ry} Z`;const items=[['蛋白质',record.protein,target.proteinTarget,'protein'],['碳水',record.carbs,target.carbTarget,'carbs'],['脂肪',record.fat,target.fatTarget,'fat']] as const;return <div className="nutrition-body"><div className="body-canvas"><svg viewBox="0 0 500 400" role="img" aria-label="今日营养体与目标轮廓"><defs><filter id="soft"><feGaussianBlur stdDeviation="8"/></filter><linearGradient id="nutri" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#e76f51"/><stop offset=".5" stopColor="#7167d9"/><stop offset="1" stopColor="#ead06f"/></linearGradient></defs><ellipse cx="250" cy="200" rx="170" ry="145" fill="none" stroke="currentColor" strokeDasharray="4 9" opacity=".24"/><motion.path animate={{d:path}} transition={{duration:.7,ease:'easeInOut'}} d={path} fill="url(#nutri)" opacity=".22" filter="url(#soft)"/><motion.path animate={{d:path}} transition={{duration:.7,ease:'easeInOut'}} d={path} fill="url(#nutri)" opacity=".78" stroke="rgba(255,255,255,.38)"/><circle cx="250" cy="200" r="3" fill="#c7ff4a"/></svg><span>目标轮廓</span></div><div className="body-stats">{items.map(([label,value,goal,key])=><button onMouseEnter={()=>setActive(key)} onMouseLeave={()=>setActive('')} className={active===key?'active':''} key={key}><i className={key}/><span>{label}</span><strong>{Math.round(value)} <small>/ {goal} 克</small></strong></button>)}</div></div>}

const labels={breakfast:'早餐',lunch:'午餐',dinner:'晚餐',snack:'加餐'}
export function MealRhythmLine({record}:{record:DailyRecord}){const [active,setActive]=useState('');const meals=[...record.meals].sort((a,b)=>a.timestamp.localeCompare(b.timestamp));return <div className="rhythm-line"><div className="rhythm-axis"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>24:00</span></div><svg viewBox="0 0 1000 170" preserveAspectRatio="none"><path d="M0 132 C180 125 260 105 420 112 S680 60 1000 98" fill="none" stroke="currentColor" opacity=".16" strokeWidth="2"/></svg>{meals.map(meal=>{const d=new Date(meal.timestamp);const minutes=d.getHours()*60+d.getMinutes();const left=minutes/1440*100;const size=Math.max(16,Math.min(48,meal.totalCalories/13));return <button key={meal.id} style={{left:`${left}%`,bottom:`${34+Math.min(62,meal.totalCalories/9)}px`,width:size,height:size}} className={active===meal.id?'active':''} onMouseEnter={()=>setActive(meal.id)} onMouseLeave={()=>setActive('')}><i/><span>{d.toTimeString().slice(0,5)}<b>{labels[meal.type]}</b><em>{Math.round(meal.totalCalories)} 千卡</em></span></button>})}</div>}

export function EnergyRibbon({record,target}:{record:DailyRecord;target:number}){const meals=['breakfast','lunch','dinner','snack'] as const;const colors=['#e76f51','#7167d9','#ead06f','#87a7a0'];let offset=50;return <div className="ribbon-flow"><svg viewBox="0 0 1000 360" role="img" aria-label="餐次到今日摄入和目标的能量流向"><defs>{colors.map((color,i)=><linearGradient id={`ribbon-${i}`} key={color}><stop stopColor={color} stopOpacity=".65"/><stop offset="1" stopColor={color} stopOpacity=".1"/></linearGradient>)}</defs>{meals.map((type,i)=>{const value=record.meals.filter(m=>m.type===type).reduce((s,m)=>s+m.totalCalories,0);const width=Math.max(2,value/target*92);const y=offset;offset+=78;return <g key={type}><text x="20" y={y+5}>{labels[type]}</text><text x="20" y={y+23} className="ribbon-value">{Math.round(value)} 千卡</text><path d={`M145 ${y} C330 ${y}, 390 ${180+(i-1.5)*10}, 515 180`} fill="none" stroke={`url(#ribbon-${i})`} strokeWidth={width}/></g>})}<circle cx="545" cy="180" r="72" fill="none" stroke="currentColor" opacity=".14"/><text x="545" y="171" textAnchor="middle" className="ribbon-label">今日摄入</text><text x="545" y="201" textAnchor="middle" className="ribbon-total">{Math.round(record.totalCalories)}</text><path d="M618 180 C720 180 750 180 820 180" fill="none" stroke="currentColor" opacity=".18" strokeWidth={Math.max(3,record.totalCalories/target*58)}/><circle cx="875" cy="180" r="55" fill="none" stroke="#c7ff4a" opacity=".55"/><text x="875" y="172" textAnchor="middle" className="ribbon-label">今日目标</text><text x="875" y="198" textAnchor="middle" className="ribbon-total">{target}</text><text x="708" y="154" textAnchor="middle" className="ribbon-value">剩余 {Math.round(target-record.totalCalories)} 千卡</text></svg></div>}
